### ISSUE TITLE
Make stats preview card responsive

### ISSUE THREAD

**Issue by Evavic44** [Evavic44/Stats-Preview-Card-Frontendmentor#4]
Make stats preview card for mobile screens

**Comment by jv18creator** [comment]
Could you share some more information on issue? `.stats` class looks good on mobile screen. Do you want to make it vertical center?

**Comment by Evavic44** [comment]
> Could you share some more information on issue? `.stats` class looks good on mobile screen. Do you want to make it vertical center?

This is a coding challenge from Frontendmentor so it has to look as identical as the design template. 
This is what it should look like on mobile screens. 👇🏾 
![mobile-design](https://user-images.githubusercontent.com/62628408/118364192-5b33bc00-b58f-11eb-88fd-d3eab943265e.jpg)

**Comment by jv18creator** [comment]
So you want the whole project to be responsive or just the `.stats` part?

**Comment by jv18creator** [comment]
Take a look, is this some you want to achieve?  @Evavic44 

![image](https://user-images.githubusercontent.com/64732692/118369263-b29e5000-b5c0-11eb-939c-104285d1c627.png)

**Comment by Evavic44** [comment]
> Take a look, is this some you want to achieve?  @Evavic44 
> 
> ![image](https://user-images.githubusercontent.com/64732692/118369263-b29e5000-b5c0-11eb-939c-104285d1c627.png)
> 

It's inverted. Check the design I posted above👆🏾

**Comment by jv18creator** [comment]
Yes, I did the `.stats` . You want to invert image and the other card component right?

**Comment by Evavic44** [comment]
> Yes, I did the `.stats` . You want to invert image and the other card component right?

I already made this responsive [here](https://github.com/Evavic44/Stats-Preview-Card-Frontendmentor/commit/edcdbed0f3e98c1842d8f2f067d4b33433724117). Sorry for replying late. 
If you're still interested, you could help me fix the footer issue;  
**Issue Link:** #5
